spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product? characterEcoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    charset: UTF-8
    allow-request-override: false
    cache: true
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  servlet: 
    multipart: 
      max-file-size: 30MB
      max-request-size: 30MB
        
server:
  port: 1314
 

 